# Interactive local setup: PostgreSQL password + lagari-be/.env + lagari-fe/.env.local
$ErrorActionPreference = "Stop"
$beRoot = Split-Path $PSScriptRoot -Parent
$feRoot = Join-Path (Split-Path $beRoot -Parent) "lagari-fe"

Write-Host "Lagari local environment setup" -ForegroundColor Cyan
Write-Host "PostgreSQL 18 is expected (service postgresql-x64-18)." -ForegroundColor DarkGray
Write-Host ""

$pgPassword = Read-Host "Enter your PostgreSQL password for user 'postgres'" -AsSecureString
$plain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
  [Runtime.InteropServices.Marshal]::SecureStringToBSTR($pgPassword)
)

$dbHost = Read-Host "DB host [127.0.0.1]"
if ([string]::IsNullOrWhiteSpace($dbHost)) { $dbHost = "127.0.0.1" }

$dbPort = Read-Host "DB port [5432]"
if ([string]::IsNullOrWhiteSpace($dbPort)) { $dbPort = "5432" }

$dbName = Read-Host "Database name [lagari]"
if ([string]::IsNullOrWhiteSpace($dbName)) { $dbName = "lagari" }

$apiPort = Read-Host "API port [4000]"
if ([string]::IsNullOrWhiteSpace($apiPort)) { $apiPort = "4000" }

$feUrl = Read-Host "Frontend URL for CORS [http://localhost:3000]"
if ([string]::IsNullOrWhiteSpace($feUrl)) { $feUrl = "http://localhost:3000" }

# Test connection with psql if available
$psql = "C:\Program Files\PostgreSQL\18\bin\psql.exe"
if (-not (Test-Path $psql)) {
  $found = Get-ChildItem "C:\Program Files\PostgreSQL" -Recurse -Filter "psql.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
  if ($found) { $psql = $found.FullName }
}

if (Test-Path $psql) {
  $env:PGPASSWORD = $plain
  $test = & $psql -U postgres -h $dbHost -p $dbPort -d postgres -tAc "SELECT 1" 2>&1
  if ($LASTEXITCODE -ne 0) {
    Write-Host "Connection failed: $test" -ForegroundColor Red
    Write-Host "Fix your password in pgAdmin or reset it, then run this script again." -ForegroundColor Yellow
    exit 1
  }
  Write-Host "PostgreSQL connection OK." -ForegroundColor Green

  $exists = & $psql -U postgres -h $dbHost -p $dbPort -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$dbName'" 2>&1
  if ($exists -ne "1") {
    & $psql -U postgres -h $dbHost -p $dbPort -d postgres -c "CREATE DATABASE $dbName;" 2>&1 | Out-Null
    Write-Host "Created database '$dbName'." -ForegroundColor Green
  }
  Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue
} else {
  Write-Host "psql.exe not found — skipping connection test. Ensure database '$dbName' exists." -ForegroundColor Yellow
}

$beEnv = @"
# Generated by scripts/setup-local-env.ps1
PORT=$apiPort
NODE_ENV=development
CORS_ORIGIN=$feUrl

DB_HOST=$dbHost
DB_PORT=$dbPort
DB_USER=postgres
DB_PASSWORD=$plain
DB_NAME=$dbName
DB_LOGGING=false

# Or use a single URL instead of DB_* vars:
# DATABASE_URL=postgresql://postgres:YOUR_PASSWORD@$dbHost`:$dbPort/$dbName

REDIS_URL=

JWT_ACCESS_SECRET=dev-lagari-access-secret-min-32-chars-long
JWT_REFRESH_SECRET=dev-lagari-refresh-secret-min-32-chars-long
JWT_ACCESS_EXPIRES=15m
JWT_REFRESH_EXPIRES=7d

SEED_ADMIN_EMAIL=admin@lagari.pk
SEED_ADMIN_PASSWORD=changeme123

# Cloudinary (optional — get keys from console.cloudinary.com)
CLOUDINARY_CLOUD_NAME=
CLOUDINARY_API_KEY=
CLOUDINARY_API_SECRET=
CLOUDINARY_FOLDER=lagari/products
"@

$beEnvPath = Join-Path $beRoot ".env"
Set-Content -Path $beEnvPath -Value $beEnv -Encoding UTF8
Write-Host "Wrote $beEnvPath" -ForegroundColor Green

$feEnv = @"
# Generated by scripts/setup-local-env.ps1
NEXT_PUBLIC_API_URL=http://localhost:$apiPort
NEXT_PUBLIC_USE_API=false
"@

$feEnvPath = Join-Path $feRoot ".env.local"
Set-Content -Path $feEnvPath -Value $feEnv -Encoding UTF8
Write-Host "Wrote $feEnvPath" -ForegroundColor Green

Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  cd lagari-be"
Write-Host "  npm run db:migrate"
Write-Host "  npm run db:seed"
Write-Host "  npm run dev"
Write-Host "  cd ../lagari-fe && npm run dev"
